name: Handle API Dispatch

on:
  repository_dispatch:
    types: [run-api]

jobs:
  handle_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Print event payload
        run: |
          echo "Name: ${{ github.event.client_payload.name }}"
          echo "Action: ${{ github.event.client_payload.action }}"
